export default
{
	EMPTY_URL:					"EMPTY_URL",
	EMPTY_ROUTINE_NAME:			"EMPTY_ROUTINE_NAME",
	EMPTY_REQUEST_METHOD:		"EMPTY_REQUEST_METHOD",
	INVALID_CALLBACK_TYPE:		"INVALID CALLBACK TYPE",
	UNKNOWN_REQUEST_METHOD:		"UNKNOWN_REQUEST_METHOD",
	FAILED_RESPONSE:			"FAILED_RESPONSE",
	NO_RESPONSE_FROM_SERVER:	"NO_RESPONSE_FROM_SERVER",
	REQUEST_CONFIG_ERROR:		"REQUEST_CONFIG_ERROR"
};