export default
{
	EMPTY_URL:				"EMPTY_URL",
	EMPTY_ROUTINE_NAME:		"EMPTY_ROUTINE_NAME",
	EMPTY_REQUEST_METHOD:	"EMPTY_REQUEST_METHOD",
	INVALID_CALLBACK_TYPE:	"INVALID CALLBACK TYPE",
	UNKNOWN_REQUEST_METHOD:	"UNKNOWN_REQUEST_METHOD",
	FAILED_JSON_RESPONSE:	"FAILED_JSON_RESPONSE",
	FETCH_ERRORS:			"FETCH_ERRORS",
	BROKEN_JSON:			"BROKEN_JSON",
};