export default
{
	GET_USER_BIO:				"GET_USER_BIO",
	GET_USER_EDUCATION:			"GET_USER_EDUCATION",
	GET_USER_SKILLS:			"GET_USER_SKILLS",
	GET_USER_WORK_EXPERIENCE:	"GET_USER_WORK_EXPERIENCE",
	GET_USER_PROJECTS:			"GET_USER_PROJECTS"
};