export default
{
	GET_USER_BIO:				"GET_USER_BIO",
	GET_USER_EDUCATION:			"GET_USER_EDUCATION",
	GET_USER_SKILLS:			"GET_USER_SKILLS",
	GET_USER_WORK_EXPERIENCE:	"GET_USER_WORK_EXPERIENCE",
	GET_USER_PROJECTS:			"GET_USER_PROJECTS",

	// API callback actions
	ON_GET_USER_BIO:				"ON_GET_USER_BIO",
	ON_GET_USER_EDUCATION:			"ON_GET_USER_EDUCATION",
	ON_GET_USER_SKILLS:				"ON_GET_USER_SKILLS",
	ON_GET_USER_WORK_EXPERIENCE:	"ON_GET_USER_WORK_EXPERIENCE",
	ON_GET_USER_PROJECTS:			"ON_GET_USER_PROJECTS"
};