export default
{
	HOME:						"HOME",
	ABOUT_ME:					"ABOUT_ME",
    ABOUT_ME_EDUCATION:			"ABOUT_ME_EDUCATION",
    ABOUT_ME_SKILLS:			"ABOUT_ME_SKILLS",
    ABOUT_ME_WORK_EXPERIENCE:	"ABOUT_ME_WORK_EXPERIENCE",
	BLOG:						"BLOG",
	PROJECTS:					"PROJECTS",
	CONTACT_ME:					"CONTACT_ME"
}